variables:
  APP_ID: io.gitlab.zehkira.Monophony
  RELEASE_BRANCH: release # Branch on which to build and deploy automatically
  DEV_BRANCH: master # Main development branch into which feature branches are squashed and merged
  FLATPAK_BRANCH: master # Branch of exported flatpak repo, same as in flatpakref file
  IMAGE: alpine:3.22.1


stages:
  - test
  - build-x86_64
  - build-aarch64
  - deploy


test:
  stage: test
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $DEV_BRANCH)
  image: ${IMAGE}
  script:
    - apk add appstream bash desktop-file-utils flatpak flatpak-builder make ruff

    - ruff check source
    - appstreamcli validate --explain --strict source/data/metainfo.xml
    - desktop-file-validate source/data/*.desktop
    - find source/locales/ | tr "\n" " " | grep -vq \.mo
    - make --directory=source/ flatpak
    - flatpak run --filesystem=$CI_PROJECT_DIR/source/tests/:ro --command=source/tests/tests.py --env=LOG_LEVELS=ERRO ${APP_ID}


.build:
  rules:
    - if: $CI_COMMIT_BRANCH == $RELEASE_BRANCH
  image: ${IMAGE}
  script:
    - apk add flatpak flatpak-builder

    - flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - gpg --list-keys --with-keygrip
    - echo "allow-preset-passphrase" >> ~/.gnupg/gpg-agent.conf
    - gpg-connect-agent reloadagent /bye
    - cat $GPG_PASSPHRASE | /usr/libexec/gpg-preset-passphrase --preset $GPG_KEY_GREP
    - gpg --import --batch ${GPG_PRIVATE_KEY}

    - flatpak-builder build --arch=${ARCH} --user --install-deps-from=flathub --gpg-sign=${GPG_KEY_ID} --disable-rofiles-fuse --disable-updates --force-clean --repo=repo --default-branch=${FLATPAK_BRANCH} $CI_PROJECT_DIR/source/data/manifest.json
    - flatpak build-bundle --arch=${ARCH} --gpg-sign=${GPG_KEY_ID} repo ${APP_ID}.flatpak --runtime-repo=flathub ${APP_ID} ${FLATPAK_BRANCH}
    - flatpak build-update-repo --gpg-sign=${GPG_KEY_ID} --generate-static-deltas --prune repo/
  artifacts:
    paths:
      - repo


build-x86_64:
  extends: .build
  stage: build-x86_64
  variables:
    ARCH: x86_64


build-aarch64:
  extends: .build
  stage: build-aarch64
  variables:
    ARCH: aarch64


pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $RELEASE_BRANCH
  image: ${IMAGE}
  script:
    - apk add rsync
    - find $BUILD_OUTPUT_PATH \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i -e "s#href=\"\/#href=\"$CI_PAGES_URL/#g" -e "s#src=\"\/#src=\"$CI_PAGES_URL/#g"
    - mkdir --parents public
    - rsync -av --exclude='public' --exclude='.git' ${CI_PROJECT_DIR}/repo/ public
  artifacts:
    paths:
      - public
