[project]
name = 'monophony'
dynamic = ['version']
requires-python = '>=3.12'

[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[tool.setuptools.dynamic]
version = {attr='monophony.__version__'}

[tool.setuptools.packages.find]
include = ['monophony*']

[tool.ruff]
builtins = ['_']
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [
	'A', 'ARG', 'ASYNC',
	'B', 'BLE',
	'C4', 'COM',
	'DTZ',
	'E', 'EM', 'EXE',
	'F', 'FA', 'FIX', 'FLY', 'FURB',
	'G',
	'I', 'ICN', 'INP', 'INT', 'ISC',
	'LOG',
	'N',
	'PERF', 'PGH', 'PIE', 'PLC', 'PLE', 'PLR', 'PLW', 'PT',
	'Q',
	'RET', 'RSE', 'RUF',
	'S', 'SIM', 'SLF', 'SLOT',
	'T20', 'TID', 'TRY',
	'UP',
	'W'
]
ignore = [
	'COM812', # missing-trailing-comma
	'PLR09', # too-many-*
	'S108', # hardcoded-temp-file
	'S311', # suspicious-non-cryptographic-random-usage
	'S603', # subprocess-without-shell-equals-true
	'S607', # start-process-with-partial-path
	'W191' # tab-indentation
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = 'single'
docstring-quotes = 'single'
multiline-quotes = 'single'

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = 'all'

[tool.ruff.lint.isort]
section-order = [
	'future', 'standard-library', 'local-folder', 'first-party', 'third-party'
]
known-first-party = ['monophony']
lines-after-imports = 2
